services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: boxbox_qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage: